version: "3"
services:
    proxy:
        image: nginx:latest
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public:/public
        ports:
            - 80:80
        links:
        - ui
    ui:
        image: node:latest
        volumes:
          - ./:/ui
        working_dir: /ui
        command: bash -c "npm install && npm start"
        environment:
            - NODE_OPTIONS=--max-old-space-size=4096
            - TOOL_NODE_FLAGS=--max-old-space-size=4096
    backend:
      stdin_open: true
      build:
        context: .
        dockerfile: backend/Dockerfile
      command: python main.py
      tty: true
      volumes:
        - ./backend:/app/:cached
        - ./backend/.docker/.ipython:/root/.ipython:cached
      environment:
        PYTHONPATH: .
      restart: on-failure
      ports:
        - 4000:4000
